from typing import overload

def sigmoid(x: float) -> float: ...
def sign(x: float | int) -> float: ...
@overload
def clamp(v: int, minv: int, maxv: int) -> int: ...
@overload
def clamp(v: float, minv: float, maxv: float) -> float: ...
def lerp(vfrom: float, vto: float, scale: float) -> float: ...
def sgt(a: float, b: float, s: float) -> float: ...
def slt(a: float, b: float, s: float) -> float: ...
def smin(a: float, b: float, k: float) -> float: ...
def smax(a: float, b: float, k: float) -> float: ...
