def jaro(s1: str, s2: str) -> float: ...
def jaro_winkler(s1: str, s2: str, prefix_scaling: float = 0.1, common_prefix_length: int = 4) -> float: ...
def jaro_winkler_default(s1: str, s2: str) -> float: ...
